[package]

name = "streets4rust"
version = "0.0.1"
authors = ["Florian Wilkens <floya@live.de>"]

[profile.release]
opt-level = 3
lto = true

[dependencies.osmpbfreader]
git = "https://github.com/TeXitoi/osmpbfreader-rs"
